<?php
/**
 * @var \Picpay\Payment\Block\Success $this
 */


/** @var \Picpay\Payment\Helper\Data $picpayHelper */
$picpayHelper = $this->getHelper();

/** @var \Magento\Sales\Model\Order $order */
$order = $this->getOrder();

$isSecure = $picpayHelper->isCurrentlySecure();
?>

<div class="callback-iframe-content">
    <?php if($picpayHelper->getMessageIframeCallback()): ?>
        <?php echo $picpayHelper->getMessageIframeCallback();?>
    <?php else: ?>
        <p>Seu pedido foi aprovado.<br/>Confira os detalhes do seu pedido a seguir ...</p>

        <?php if($order && $order->getId()): ?>
            <script type="text/javascript">
                setTimeout(function () {
                    window.top.location.href = '<?php echo $this->getUrl("sales/order/view", array('order_id' => $order->getId(), '_secure' => $isSecure)); ?>';
                }, 2500);
            </script>
        <?php endif ?>
    <?php endif; ?>
</div>
<style>
    .callback-iframe-content {
        padding: 100px 20px;
        font-size: 16px;
        text-align: center;
    }
    .callback-iframe-content * {
        text-align: center;
    }
</style>