<?php

/**
 * @var \Picpay\Payment\Block\Success $this
 */

/** @var \Picpay\Payment\Helper\Data $picpayHelper */
$picpayHelper = $this->getHelper();

/** @var \Magento\Sales\Model\Order $order */
$order = $this->getOrder();

$isSecure = $picpayHelper->isCurrentlySecure();
?>

<?php if($order && $order->getId()): ?>
    <?php
    /** @var \Magento\Sales\Model\Order\Payment $payment */
    $payment = $order->getPayment();
    $paymentUrl = $payment->getAdditionalInformation("paymentUrl")
    ?>

    <?php if ($paymentUrl): ?>
        <?php
        $qrcodeSource = $payment->getAdditionalInformation("qrcode");
        $onPageWidth = $picpayHelper->getQrcodeOnpageWidth();
        $imageSize = $onPageWidth ?: $picpayHelper::DEFAULT_QRCODE_WIDTH ;
        $style = "margin-left: auto; margin-right: auto;";
        ?>

        <h3><?= __('Pay with PicPay') ?></h3>
        <p><?= __('Open the PicPay app on your smartphone and scan the QRCode below:') ?></p>
        <p>
            <?= $picpayHelper->generateQrCode($qrcodeSource, (string) $imageSize,  $style); ?>
        </p>
        <?= $picpayHelper->getMessageOnpageSuccess(); ?>
    <?php endif; ?>
<?php endif; ?>
