<!-- Custom template for PicPay Payment -->

<img width="150px" src="https://picpay.github.io/picpay-docs-digital-payments/img/PP-logo.png" alt="PicPay"
style=" border: 0; padding: 10px;" />
<br/>
<p><?php echo __('Not familiar with PicPay ?')?>
    <a href="https://www.picpay.com/site" target="_blank"><?php echo __('Click here')?></a>
    <?php echo __(' and download now to make your payment.')?></p>