<p><?php echo __("Picpay Payment") ?></p>

<?php if($this->getPaymentUrl()): ?>
    <h3><?= __('Pay with PicPay') ?>Pague com PicPay</h3>
    <p><?= __('Abra o PicPay em seu telefone e escaneie o código abaixo:') ?></p>
    <p>
        <a href="<?php echo $this->getPaymentUrl(); ?>" target="_blank" title="<?= __('Payment QR Code') ?>">
            <?php echo $this->getQrcode() ?>
        </a>
    </p>
    <p>
        <a href="<?php echo $this->getPaymentUrl(); ?>" target="_blank" title="<?= __("Link to complete the order on PicPay checkout") ?>">
            <?= __('Click here') ?>
        </a>
        <?= __('if you you want to complete the order on PicPay checkout') ?>
    </p>
<?php endif; ?>

<?php if($this->getAuthorizationId()): ?>
    <p><?php echo __("Authorization Id"); ?>: <?php echo $this->getAuthorizationId() ?></p>
<?php endif; ?>

<?php if($this->getCancellationId()): ?>
    <p><?php echo __("Cancellation Id"); ?>: <?php echo $this->getCancellationId() ?></p>
<?php endif; ?>

