<p><?= __("Picpay") ?></p>

<?php if($this->getPaymentUrl()): ?>
    <p>
        <a href="<?php echo $this->getPaymentUrl(); ?>" target="_blank">
            <?php echo $this->getQrcode() ?>
        </a>
    </p>
    <p>
        <a href="<?php echo $this->getPaymentUrl(); ?>" target="_blank"><?php echo __("Payment Link") ?></a>
    </p>
<?php endif; ?>

<?php if($this->getAuthorizationId()): ?>
    <p><?php echo __("Authorization Id"); ?>: <?php echo $this->getAuthorizationId() ?></p>
<?php endif; ?>

<?php if($this->getCancellationId()): ?>
    <p><?php echo __("Cancellation Id"); ?>: <?php echo $this->getCancellationId() ?></p>
<?php endif; ?>
